### PR TITLE
Handle leading (URL encoded) spaces

### PR DESCRIPTION
**Pull request by maxbeizer**
@raul  I'm not sure I like the implementation I chose, but this should strip out the encoded spaces at the start of the ID string. Thoughts?

### CODE REVIEW

**Comment by raul** [comment]
I don't see anything wrong in the implementation but I'm not sure how to deal with this change in the functionality @maxbeizer: it seems to fix a very specific case (encoded space) for a specific scenario (user prefers the formatter to filter out invalid chars, rather than raising an exception).

Should the gem filter out any invalid non-alphanumeric character, not only encoded spaces? Only at the beginning, or in the whole string? Perhaps the gem should be opinionated on that and remain strict, leaving the specific filtering in hands of the user as the filtering criteria to be applied seems very dependent of the context?

**Comment by maxbeizer** [comment]
The more I think about it, the more this should not be in this gem. I think the filtering of the input should be in the user's hands. In a UNIX-y way, this gem should really just do the one thing 15 <--> 18.

**Comment by raul** [comment]
I think I agree, and that makes me think that I chose a bad name for the gem: `salesforce_id_converter` would have been more appropriate.

**Comment by maxbeizer** [comment]
wcyd

**Pull request closed without merging**
